apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: polymetrie-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sylcantor/k8s-app:v1.2
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:vIb0KKfqE0@pg-postgresql:5432/postgres
        - name: REDIS_HOST
          value: redis-master
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "t8mJPkJxOe"

