apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-monitor
  labels:
    release: prometheus-stack 
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - polymetrie-c
  endpoints:
  - port: "8080" 
    interval: 30s
    path: /metrics
