prometheus:
  enabled: true
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: "csi-cinder-high-speed"  # Default storage class in cluster
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 16Gi
    retention: 7d 

grafana:
  adminPassword: "prom-operator"
  persistence:
    enabled: true
    storageClassName: "csi-cinder-high-speed" 
    accessModes: ["ReadWriteOnce"]
    size: 1Gi
