apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: polymetrie-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: cloudblip06/polymetrie:v1.3
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:xYOa2gvS8N@db-pg-postgresql:5432/postgres
        - name: REDIS_HOST
          value: redis-master
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "9DoTmFKdQu"
        resources:
          requests:
            cpu: "500m"
