apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-monitor
  namespace: polymetrie-c
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - polymetrie-c
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
