name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: TAG="polymetrie:$(date +%s)" && docker build backend/ --file backend/Dockerfile --tag polymetrie:$TAG
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    - name: Push Api Docker image
      run: |
       docker images
       docker tag $TAG ${{ secrets.DOCKERHUB_USERNAME }}/backend-polymetrie
       docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-polymetrie  
