name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-save-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.save-tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        TAG="polymetrie:$(date +%s)"
        docker build backend/ --file backend/Dockerfile --tag $TAG
        echo $TAG > tag.txt
    - name: Save TAG to output
      id: save-tag
      run: echo "::set-output name=tag::$(cat tag.txt)"
    - uses: actions/upload-artifact@v2
      with:
        name: tag
        path: tag.txt

  login-and-push-image:
    needs: build-and-save-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v2
      with:
        name: tag
    - name: Read TAG from file
      id: tag
      run: echo "TAG=$(cat tag.txt)" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    - name: Push Api Docker image
      run: |
       docker images
       docker tag ${{ env.TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/backend-polymetrie
       docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-polymetrie
