name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          TAG="polymetrie:$(date +%s)"
          docker build backend/ --file backend/Dockerfile --tag polymetrie:v1.3
          docker save $TAG > image.tar
          echo $TAG > tag.txt
      - name: Upload Docker image as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: image.tar
      - name: Save TAG to output
        id: save-tag
        run: echo "::set-output name=tag::$(cat tag.txt)"
      - uses: actions/upload-artifact@v2
        with:
          name: tag
          path: tag.txt

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image from artifacts
        uses: actions/download-artifact@v2
        with:
          name: docker-image
      - name: Download TAG from artifacts
        uses: actions/download-artifact@v2
        with:
          name: tag
      - name: Load Docker image
        run: |
          docker load < image.tar
      - name: Read TAG from file
        run: |
          TAG=$(cat tag.txt)
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Push Api Docker image
        run: |
          docker tag polymetrie:v1.3 ${{ secrets.DOCKERHUB_USERNAME }}/backend-polymetrie
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-polymetrie
