name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build backend/ --file backend/Dockerfile --tag polymetrie:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: cloudblip06
        password: ${{ secrets.DOCKERHUB_PASS }}
    - name: Push Api Docker image
      run: |
       docker images
       docker tag strat-api cloudblip06/backend-polymetrie
       docker push cloudblip06/backend-polymetrie  
